name: Publish

on:
  push:
    branches-ignore:
    - main

jobs:
  dhub:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: foxcapades/ubuntu-corretto:${{ github.ref_name }}
        labels: io.foxcapades.git-commit=${{ github.sha }}
